### ISSUE TITLE
Unresponsive File

### ISSUE THREAD

**Issue by therealOri** [Traumatism/Dropper#6]
Just decided to try out the obfuscation with an actual project of mine. [PassGen](https://github.com/therealOri/PassGen) and when I ran the main python file. It gave no errors and no output.

<br />
<br />

# Steps to reproduce:
> - Clone PassGen repo
> - Make virtual environment, install packages, get all that stuff set up.
> - Run passgen.py once and let it set up its .env file.
> - Use dropper to obfuscate passgen.py
> - Move obf_passgen.py into PassGen Directory, delete passgen.py, and rename obf_passgen.py to passgen.py.
> - Run the new obfuscated passgen.py file in the PassGen directory.

<br />
<br />

# What happens
- No output, no errors, nothing happens.
![image](https://user-images.githubusercontent.com/45724082/162836322-81b87150-40d6-4bab-9484-3842cc03cd51.png)

<br />

# What should happen
- Run code and pull up an interactive menu with options.
![image](https://user-images.githubusercontent.com/45724082/162836403-1b44f193-47cc-4b60-bd84-403dab570289.png)

__ __

**Comment by therealOri** [comment]
Also, unrelated...
dropper needs packages `rich` and `typer` installed in order to work.

**Comment by lhitori** [comment]
AAAAH that another lambda issue

**Comment by therealOri** [comment]
Additionally. Here is some more unrelated "fun". 

Basically because I am on linux instead of  windows or mac...I don't get `dll`/`pyd` files. Instead I get `.so` files. I wanted to obfuscate a .py file (following code) then turn it into a .so file to be imported and used in another python file. [Making of a .so file (my source)](https://programmerall.com/article/85961512470/) idk how you'd do it on Mac or on windows but i'm using cython. After I have obfuscated my code and then turned it into a .so file. I try to import it and run my main.py file and I get the following error.

<br />
<br />

# Code to be obfuscated and turned into a .so file.
> The file name this code will be in is `test.py`
```python
def test():
    print("hello python!")
     
def add(a, b):
    print(a + b)
    return a + b
```
<br />
<br />

# Main.py code file.
```python
import test

test.test()
```

<br />
<br />

# Error message after obfuscation.
```zsh
Traceback (most recent call last):
  File "/home/ori/Desktop/Projects/currently_active/so_Testing/main.py", line 1, in <module>
    import test
  File "test.py", line 6, in test.lambda
  File "test.py", line 6, in test.lambda
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 40: invalid start byte
```
> test.py does not exist in the current directory so idk what is happening to make this an issue but maybe it's worth it to bring attention to. If this is not an issue that is being caused by dropper and instead cython being weird then feel free to ignore this...idk.
